//
//  PCHUNews.m
//  ABHUNews
//
//  Created by Blake+Albert on 1/24/15.
//  Copyright (c) 2015 FDB. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "PCHUNews.h"


@implementation PCHUNews

#pragma mark Cache

static UIImage* _imageOfATMaterialCells = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawATMaterialCells
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* shadowTableCellColor = [UIColor colorWithRed: 0.032 green: 0.032 blue: 0.032 alpha: 0.141];

    //// Shadow Declarations
    UIColor* shadowTableCell = shadowTableCellColor;
    CGSize shadowTableCellOffset = CGSizeMake(2.1, 4.1);
    CGFloat shadowTableCellBlurRadius = 5;

    //// RectangleContainer Drawing
    UIBezierPath* rectangleContainerPath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(7, 7, 587, 284) cornerRadius: 5];
    CGContextSaveGState(context);
    CGContextSetShadowWithColor(context, shadowTableCellOffset, shadowTableCellBlurRadius, [shadowTableCell CGColor]);
    [UIColor.whiteColor setFill];
    [rectangleContainerPath fill];
    CGContextRestoreGState(context);
}

#pragma mark Generated Images

+ (UIImage*)imageOfATMaterialCells
{
    if (_imageOfATMaterialCells)
        return _imageOfATMaterialCells;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(600, 303), NO, 0.0f);
    [PCHUNews drawATMaterialCells];

    _imageOfATMaterialCells = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfATMaterialCells;
}

#pragma mark Customization Infrastructure

- (void)setATMaterialCellsTargets: (NSArray*)aTMaterialCellsTargets
{
    _aTMaterialCellsTargets = aTMaterialCellsTargets;

    for (id target in self.aTMaterialCellsTargets)
        [target setImage: PCHUNews.imageOfATMaterialCells];
}


@end
