//
//  PCHUNews.h
//  ABHUNews
//
//  Created by Blake+Albert on 1/24/15.
//  Copyright (c) 2015 FDB. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PCHUNews : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* aTMaterialCellsTargets;

// Generated Images
+ (UIImage*)imageOfATMaterialCells;

@end
